name: instagram_media
description: Authenticates a Instagram user and fetches their media via the Instagram Basic API.
version: 0.0.11
homepage: https://www.idality.dev

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.3
  flutter_webview_plugin: ^0.3.11
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
